### ISSUE TITLE
Angular fire injector error

### ISSUE THREAD

**Issue by MarinoRaul** [angular/angularfire2#1062]
Runtime Error
undefined is not a function
Stack
TypeError: undefined is not a function
    at _firebaseAppFactory (http://localhost:8100/build/main.js:139685:16)
    at _callFactory (http://localhost:8100/build/main.js:11701:17)
    at _createProviderInstance$1 (http://localhost:8100/build/main.js:11640:26)
    at resolveNgModuleDep (http://localhost:8100/build/main.js:11622:17)
    at _callFactory (http://localhost:8100/build/main.js:11697:34)
    at _createProviderInstance$1 (http://localhost:8100/build/main.js:11640:26)
    at resolveNgModuleDep (http://localhost:8100/build/main.js:11622:17)
    at _createClass (http://localhost:8100/build/main.js:11677:32)
    at _createProviderInstance$1 (http://localhost:8100/build/main.js:11637:26)
    at resolveNgModuleDep (http://localhost:8100/build/main.js:11622:17)
Ionic Framework: ^3.5.0
Ionic App Scripts: 1.3.12
Angular Core: ^4.2.5
Angular Compiler CLI: ^4.2.5
Node: 7.6.0
OS Platform: Linux 4.4
Navigator Platform: Linux x86_64
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) 

---------------------------------------------

https://github.com/angular/angularfire2/blob/master/docs/Auth-with-Ionic3-Angular4.md

**Comment by noboddee** [comment]
@MarinoRaul are you find a solution ? I have the same issue..

**Comment by davideast** [comment]
@MarinoRaul This should not be a problem in the latest version. If so please open a new issue 👍
