### ISSUE TITLE
Build broken with Typescript 2.4

### ISSUE THREAD

**Issue by jamesdaniels** [angular/angularfire2#1072]
### Version info

**Angular:** n/a

**Firebase:** n/a

**AngularFire:** master

**Other (e.g. Ionic/Cordova, Node, browser, operating system):** typescript 2.4

### How to reproduce these conditions

    npm install
    npm run build

**Sample data and security rules**

n/a

### Debug output

```
src/database/firebase_list_factory.ts(115,51): error TS2345: Argument of type '(obs: Observer<any[]>) => () => void' is not assignable to parameter of type '(<R>(subscriber: Subscriber<R>) => void | Function | Subscription) | undefined'.
  Type '(obs: Observer<any[]>) => () => void' is not assignable to type '<R>(subscriber: Subscriber<R>) => void | Function | Subscription'.
    Types of parameters 'obs' and 'subscriber' are incompatible.
      Type 'Subscriber<R>' is not assignable to type 'Observer<any[]>'.
        Types of property 'next' are incompatible.
          Type '(value?: R | undefined) => void' is not assignable to type '(value: any[]) => void'.
            Types of parameters 'value' and 'value' are incompatible.
              Type 'any[]' is not assignable to type 'R | undefined'.
                Type 'any[]' is not assignable to type 'R'.
```

### Expected behavior

not that.

### Actual behavior

that.

**Comment by ericel** [comment]
I am having the same issue trying to run `npm run build`. Works just well with just `ng build`.

I am using angular-ssr for my angular-cli project.

```
Unhandled Promise rejection: n.removeEventListener is not a function ; Zone: <root> ; Task: Promise.then ; Value: { TypeError: n.removeEven
tListener is not a function
    at C:\Users\S\AppData\Local\Temp\47aec918d3\webpack:\~\firebase\auth.js:28:843
    at C:\Users\S\AppData\Local\Temp\47aec918d3\webpack:\~\firebase\auth.js:28:880
    at C:\Users\S\AppData\Local\Temp\47aec918d3\webpack:\~\firebase\auth.js:277:366
    at Object.eo/D (C:\Users\S\AppData\Local\Temp\47aec918d3\webpack:\~\firebase\auth.js:278:2)
    at e (C:\Users\S\AppData\Local\Temp\47aec918d3\webpack:\webpack\bootstrap 9f2c19ec88d22c4d7cc6:19:1)
    at Object.RVyb (C:\Users\S\AppData\Local\Temp\47aec918d3\webpack:\0.js:6968:72)
    at e (C:\Users\S\AppData\Local\Temp\47aec918d3\webpack:\webpack\bootstrap 9f2c19ec88d22c4d7cc6:19:1)
    at Object.+rnp (C:\Users\S\AppData\Local\Temp\47aec918d3\webpack:\0.js:316:89)
    at e (C:\Users\S\AppData\Local\Temp\47aec918d3\webpack:\webpack\bootstrap 9f2c19ec88d22c4d7cc6:19:1)
    at Object.Cos1 (C:\Users\S\AppData\Local\Temp\47aec918d3\webpack:\0.js:6442:76)
    at e (C:\Users\S\AppData\Local\Temp\47aec918d3\webpack:\webpack\bootstrap 9f2c19ec88d22c4d7cc6:19:1)
    at Object.32 (C:\Users\S\AppData\Local\Temp\47aec918d3\webpack:\0.js:3524:18)
    at e (C:\Users\S\AppData\Local\Temp\47aec918d3\webpack:\webpack\bootstrap 9f2c19ec88d22c4d7cc6:19:1)
    at C:\Users\S\AppData\Local\Temp\47aec918d3\webpack:\webpack\bootstrap 9f2c19ec88d22c4d7cc6:65:1
    at Object.<anonymous> (C:\Users\S\AppData\Local\Temp\47aec918d3\webpack:\webpack\bootstrap 9f2c19ec88d22c4d7cc6:65:1)
    at Module._compile (module.js:570:32)
  __zone_symbol__currentTask:
   ZoneTask {
     _zone:
      Zone {
        _properties: {},
        _parent: null,
        _name: '<root>',
        _zoneDelegate: [Object] },
     runCount: 0,
     _zoneDelegates: null,
     _state: 'notScheduled',
     type: 'microTask',
     source: 'Promise.then',
     data: undefined,
     scheduleFn: undefined,
     cancelFn: null,
     callback: [Function],
     invoke: [Function] } } TypeError: n.removeEventListener is not a function
    at C:\Users\S\AppData\Local\Temp\47aec918d3\webpack:\~\firebase\auth.js:28:843
    at C:\Users\S\AppData\Local\Temp\47aec918d3\webpack:\~\firebase\auth.js:28:880
    at C:\Users\S\AppData\Local\Temp\47aec918d3\webpack:\~\firebase\auth.js:277:366
    at Object.eo/D (C:\Users\S\AppData\Local\Temp\47aec918d3\webpack:\~\firebase\auth.js:278:2)
    at e (C:\Users\S\AppData\Local\Temp\47aec918d3\webpack:\webpack\bootstrap 9f2c19ec88d22c4d7cc6:19:1)
    at Object.RVyb (C:\Users\S\AppData\Local\Temp\47aec918d3\webpack:\0.js:6968:72)
    at e (C:\Users\S\AppData\Local\Temp\47aec918d3\webpack:\webpack\bootstrap 9f2c19ec88d22c4d7cc6:19:1)
    at Object.+rnp (C:\Users\S\AppData\Local\Temp\47aec918d3\webpack:\0.js:316:89)
    at e (C:\Users\S\AppData\Local\Temp\47aec918d3\webpack:\webpack\bootstrap 9f2c19ec88d22c4d7cc6:19:1)
    at Object.Cos1 (C:\Users\S\AppData\Local\Temp\47aec918d3\webpack:\0.js:6442:76)
    at e (C:\Users\S\AppData\Local\Temp\47aec918d3\webpack:\webpack\bootstrap 9f2c19ec88d22c4d7cc6:19:1)
    at Object.32 (C:\Users\S\AppData\Local\Temp\47aec918d3\webpack:\0.js:3524:18)
    at e (C:\Users\S\AppData\Local\Temp\47aec918d3\webpack:\webpack\bootstrap 9f2c19ec88d22c4d7cc6:19:1)
    at C:\Users\S\AppData\Local\Temp\47aec918d3\webpack:\webpack\bootstrap 9f2c19ec88d22c4d7cc6:65:1
    at Object.<anonymous> (C:\Users\S\AppData\Local\Temp\47aec918d3\webpack:\webpack\bootstrap 9f2c19ec88d22c4d7cc6:65:1)
    at Module._compile (module.js:570:32)
```
