### ISSUE TITLE
Unhandled Promise rejection: n.removeEventListener is not a function, angularfire2/ angular-ssr

### ISSUE THREAD

**Issue by ericel** [angular/angularfire2#1077]
**Angular:*4.0.0*

**Firebase:*^4.1.3*

**AngularFire:*^4.0.0-rc.1*

I generated a new project with the latest angular-cli
When I do `'npm run build'` without , angularfire2, it builds well with the expected results. But when I do the same with angularfire2, I get the following error:
```
> ng-render

[info] Rendering application from source (working path: C:\Users\S\AppData\Local\Temp\f38a8c8759a77)
Unhandled Promise rejection: n.removeEventListener is not a function ; Zone: <root> ; Task: Promise.then ; Value: { TypeError: n.removeEventListener is not a function
    at C:\Users\S\AppData\Local\Temp\f38a8c8759a77\webpack:\~\firebase\auth.js:28:843
    at C:\Users\S\AppData\Local\Temp\f38a8c8759a77\webpack:\~\firebase\auth.js:28:880
    at C:\Users\S\AppData\Local\Temp\f38a8c8759a77\webpack:\~\firebase\auth.js:277:366
    at Object.eo/D (C:\Users\S\AppData\Local\Temp\f38a8c8759a77\webpack:\~\firebase\auth.js:278:2)
    at e (C:\Users\S\AppData\Local\Temp\f38a8c8759a77\webpack:\webpack\bootstrap 19b8eee3ecbed18ba62f:19:1)
    at Object.RVyb (C:\Users\S\AppData\Local\Temp\f38a8c8759a77\webpack:\0.js:15532:72)
    at e (C:\Users\S\AppData\Local\Temp\f38a8c8759a77\webpack:\webpack\bootstrap 19b8eee3ecbed18ba62f:19:1)
    at Object.+rnp (C:\Users\S\AppData\Local\Temp\f38a8c8759a77\webpack:\0.js:673:89)
    at e (C:\Users\S\AppData\Local\Temp\f38a8c8759a77\webpack:\webpack\bootstrap 19b8eee3ecbed18ba62f:19:1)
    at Object.Cos1 (C:\Users\S\AppData\Local\Temp\f38a8c8759a77\webpack:\0.js:11053:77)
    at e (C:\Users\S\AppData\Local\Temp\f38a8c8759a77\webpack:\webpack\bootstrap 19b8eee3ecbed18ba62f:19:1)
    at Object.44 (C:\Users\S\AppData\Local\Temp\f38a8c8759a77\webpack:\0.js:7379:18)
    at e (C:\Users\S\AppData\Local\Temp\f38a8c8759a77\webpack:\webpack\bootstrap 19b8eee3ecbed18ba62f:19:1)
    at C:\Users\S\AppData\Local\Temp\f38a8c8759a77\webpack:\webpack\bootstrap 19b8eee3ecbed18ba62f:65:1
    at Object.<anonymous> (C:\Users\S\AppData\Local\Temp\f38a8c8759a77\webpack:\webpack\bootstrap 19b8eee3ecbed18ba62f:65:1)
    at Module._compile (module.js:570:32)
  __zone_symbol__currentTask:
   ZoneTask {
     _zone:
      Zone {
        _properties: {},
        _parent: null,
        _name: '<root>',
        _zoneDelegate: [Object] },
     runCount: 0,
     _zoneDelegates: null,
     _state: 'notScheduled',
     type: 'microTask',
     source: 'Promise.then',
     data: undefined,
     scheduleFn: undefined,
     cancelFn: null,
     callback: [Function],
     invoke: [Function] } } TypeError: n.removeEventListener is not a function
    at C:\Users\S\AppData\Local\Temp\f38a8c8759a77\webpack:\~\firebase\auth.js:28:843
    at C:\Users\S\AppData\Local\Temp\f38a8c8759a77\webpack:\~\firebase\auth.js:28:880
    at C:\Users\S\AppData\Local\Temp\f38a8c8759a77\webpack:\~\firebase\auth.js:277:366
    at Object.eo/D (C:\Users\S\AppData\Local\Temp\f38a8c8759a77\webpack:\~\firebase\auth.js:278:2)
    at e (C:\Users\S\AppData\Local\Temp\f38a8c8759a77\webpack:\webpack\bootstrap 19b8eee3ecbed18ba62f:19:1)
    at Object.RVyb (C:\Users\S\AppData\Local\Temp\f38a8c8759a77\webpack:\0.js:15532:72)
    at e (C:\Users\S\AppData\Local\Temp\f38a8c8759a77\webpack:\webpack\bootstrap 19b8eee3ecbed18ba62f:19:1)
    at Object.+rnp (C:\Users\S\AppData\Local\Temp\f38a8c8759a77\webpack:\0.js:673:89)
    at e (C:\Users\S\AppData\Local\Temp\f38a8c8759a77\webpack:\webpack\bootstrap 19b8eee3ecbed18ba62f:19:1)
    at Object.Cos1 (C:\Users\S\AppData\Local\Temp\f38a8c8759a77\webpack:\0.js:11053:77)
    at e (C:\Users\S\AppData\Local\Temp\f38a8c8759a77\webpack:\webpack\bootstrap 19b8eee3ecbed18ba62f:19:1)
    at Object.44 (C:\Users\S\AppData\Local\Temp\f38a8c8759a77\webpack:\0.js:7379:18)
    at e (C:\Users\S\AppData\Local\Temp\f38a8c8759a77\webpack:\webpack\bootstrap 19b8eee3ecbed18ba62f:19:1)
    at C:\Users\S\AppData\Local\Temp\f38a8c8759a77\webpack:\webpack\bootstrap 19b8eee3ecbed18ba62f:65:1
    at Object.<anonymous> (C:\Users\S\AppData\Local\Temp\f38a8c8759a77\webpack:\webpack\bootstrap 19b8eee3ecbed18ba62f:65:1)
    at Module._compile (module.js:570:32)
```
Note: I have other modules like material2, ng2-pipes that work just well with angular-ssr.

Is there any work around to get angular-ssr to work with angularfire2?

**Comment by nsantosdaveiga** [comment]
I have the same problem do you find something ?

**Comment by ericel** [comment]
No .. not yet!  Seems at the current state of things it's  gonna be a tough
one. I read somewhere that Angularfire2 needs some changes to support
universal.  So maybe it's  just to wait.

**Comment by davideast** [comment]
Follow #1073
