### ISSUE TITLE
Plunkr listed in readme produces syntax error : (

### ISSUE THREAD

**Issue by katowulf** [angular/angularfire2#1097]
### Version info
See [Plunkr](http://plnkr.co/edit/OXSAwUj75gzBpxUIgZ8d?p=preview)

### How to reproduce these conditions

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**
[Plunkr](http://plnkr.co/edit/OXSAwUj75gzBpxUIgZ8d?p=preview), just load it and look at the JS console.

**Steps to set up and reproduce**
I reproduced this by simply taking the [existing Plunkr](http://plnkr.co/edit/8yY4tH?p=preview) in the [README](https://github.com/angular/angularfire2) and adding my creds as explained in the comments.

**Sample data and security rules**
n/a

### Debug output

** Errors in the JavaScript console **

Error: Can't resolve all parameters for AppComponent: (?).
	    at syntaxError (https://unpkg.com/@angular/compiler/bundles/compiler.umd.js:1725:34) [<root>]
	    at CompileMetadataResolver._getDependenciesMetadata (https://unpkg.com/@angular/compiler/bundles/compiler.umd.js:15800:35) [<root>]
	    at CompileMetadataResolver._getTypeMetadata (https://unpkg.com/@angular/compiler/bundles/compiler.umd.js:15668:26) [<root>]
	    at CompileMetadataResolver.getNonNormalizedDirectiveMetadata (https://unpkg.com/@angular/compiler/bundles/compiler.umd.js:15263:24) [<root>]
	    at CompileMetadataResolver._getEntryComponentMetadata (https://unpkg.com/@angular/compiler/bundles/compiler.umd.js:15922:45) [<root>]
	    at eval (https://unpkg.com/@angular/compiler/bundles/compiler.umd.js:15504:110) [<root>]
	    at Array.map (native) [<root>]
	    at CompileMetadataResolver.getNgModuleMetadata (https://unpkg.com/@angular/compiler/bundles/compiler.umd.js:15504:73) [<root>]
	    at JitCompiler._loadModules (https://unpkg.com/@angular/compiler/bundles/compiler.umd.js:26830:70) [<root>]
	    at JitCompiler._compileModuleAndComponents (https://unpkg.com/@angular/compiler/bundles/compiler.umd.js:26803:36) [<root>]
	    at JitCompiler.compileModuleAsync (https://unpkg.com/@angular/compiler/bundles/compiler.umd.js:26732:37) [<root>]
	    at PlatformRef_._bootstrapModuleWithZone (https://unpkg.com/@angular/core/bundles/core.umd.js:4568:25) [<root>]
	    at PlatformRef_.bootstrapModule (https://unpkg.com/@angular/core/bundles/core.umd.js:4554:21) [<root>]
	    at Object.eval (http://run.plnkr.co/27iXZTT3rlETmedN/app/main.ts!transpiled:5:10) [<root>]
	Evaluating http://run.plnkr.co/27iXZTT3rlETmedN/app/main.ts
	Error loading http://run.plnkr.co/27iXZTT3rlETmedN/app/main.ts

** Output from `firebase.database().enableLogging(true);` **
n/a

** Screenshots **
n/a

### Expected behavior
Should present a list of books per the example.

### Actual behavior
JS Console error.

**Comment by katowulf** [comment]
Sync with @davideast before doing any work here. He has plans in flight.

**Comment by jamesdaniels** [comment]
#947

**Comment by davideast** [comment]
Almost fixed with #1088.

**Comment by davideast** [comment]
Fixed! And we'll start using Stackblitz from now on.

https://stackblitz.com/edit/angular-2ed5zx

**Comment by katowulf** [comment]
Woot! 🚀🚀🚀
