### ISSUE TITLE
Getting BroccoliTypeScriptCompiler error

### ISSUE THREAD

**Issue by kdavidson007** [angular/angularfire2#134]
When I follow the "10 steps to AngularFire2" instructions, I get the following error:

```
The Broccoli Plugin: [BroccoliTypeScriptCompiler] failed with:
Error: Typescript found the following errors:
  /Users/me/Documents/apps/ntf/tmp/broccoli_type_script_compiler-input_base_path-WVEsO8cN.tmp/0/src/client/app/ntf.spec.ts (8, 16): Property 'defaultMeaning' does not exist on type 'NtfApp'.
  /Users/me/Documents/apps/ntf/tmp/broccoli_type_script_compiler-input_base_path-WVEsO8cN.tmp/0/src/client/app/ntf.spec.ts (13, 18): Property 'meaningOfLife' does not exist on type 'NtfApp'.
  /Users/me/Documents/apps/ntf/tmp/broccoli_type_script_compiler-input_base_path-WVEsO8cN.tmp/0/src/client/app/ntf.spec.ts (14, 18): Property 'meaningOfLife' does not exist on type 'NtfApp'.
  /Users/me/Documents/apps/ntf/tmp/broccoli_type_script_compiler-input_base_path-WVEsO8cN.tmp/0/src/client/app.ts (6, 19): Expression expected.
  /Users/me/Documents/apps/ntf/tmp/broccoli_type_script_compiler-input_base_path-WVEsO8cN.tmp/0/src/client/app.ts (6, 11): Argument of type 'NtfApp' is not assignable to parameter of type 'Type'.
  Property 'apply' is missing in type 'NtfApp'.
    at BroccoliTypeScriptCompiler._doIncrementalBuild (/Users/me/Documents/apps/ntf/node_modules/angular-cli/lib/broccoli/broccoli-typescript.js:110:19)
    at BroccoliTypeScriptCompiler.build (/Users/me/Documents/apps/ntf/node_modules/angular-cli/lib/broccoli/broccoli-typescript.js:44:10)
    at /Users/me/Documents/apps/ntf/node_modules/angular-cli/node_modules/broccoli-caching-writer/index.js:152:21
    at lib$rsvp$$internal$$tryCatch (/Users/me/Documents/apps/ntf/node_modules/angular-cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/me/Documents/apps/ntf/node_modules/angular-cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (/Users/me/Documents/apps/ntf/node_modules/angular-cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (/Users/me/Documents/apps/ntf/node_modules/angular-cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:1198:9)
    at nextTickCallbackWith0Args (node.js:453:9)
    at process._tickCallback (node.js:382:13)

The broccoli plugin was instantiated at: 
    at BroccoliTypeScriptCompiler.Plugin (/Users/me/Documents/apps/ntf/node_modules/angular-cli/node_modules/broccoli-caching-writer/node_modules/broccoli-plugin/index.js:10:31)
    at BroccoliTypeScriptCompiler.CachingWriter [as constructor] (/Users/me/Documents/apps/ntf/node_modules/angular-cli/node_modules/broccoli-caching-writer/index.js:21:10)
    at BroccoliTypeScriptCompiler (/Users/me/Documents/apps/ntf/node_modules/angular-cli/lib/broccoli/broccoli-typescript.js:25:35)
    at Angular2App._getTsTree (/Users/me/Documents/apps/ntf/node_modules/angular-cli/lib/broccoli/angular2-app.js:255:18)
    at Angular2App.toTree (/Users/me/Documents/apps/ntf/node_modules/angular-cli/lib/broccoli/angular2-app.js:42:23)
    at module.exports (/Users/me/Documents/apps/ntf/angular-cli-build.js:12:14)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (/Users/me/Documents/apps/ntf/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:55:19)
    at Class.module.exports.Task.extend.init (/Users/me/Documents/apps/ntf/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:89:10)
    at new Class (/Users/me/Documents/apps/ntf/node_modules/angular-cli/node_modules/angular-cli/node_modules/core-object/core-object.js:18:12)
    at Class.module.exports.Task.extend.run (/Users/me/Documents/apps/ntf/node_modules/angular-cli/node_modules/angular-cli/lib/tasks/serve.js:15:19)
```

**Comment by kazkis** [comment]
Hi @kdavidson007 , you probably forgot to remove the angle brackets from `<MyAppClass>` in you `app.ts` file (step 7).

**Comment by Haroenv** [comment]
Oh, could that be made clearer in the documentation in the readme, I just lost a significant amount of time to that.
