### ISSUE TITLE
ERROR in Error: Metadata version mismatch for module */node_modules/angularfire2/index.d.ts, found version 4, expected 3, resolving symbol AppModule 

### ISSUE THREAD

**Issue by Upskxkit** [angular/angularfire2#1397]
{
  "name": "app",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^4.2.4",
    "@angular/common": "^4.2.4",
    "@angular/compiler": "^4.2.4",
    "@angular/core": "^4.2.4",
    "@angular/forms": "^4.2.4",
    "@angular/http": "^4.2.4",
    "@angular/platform-browser": "^4.2.4",
    "@angular/platform-browser-dynamic": "^4.2.4",
    "@angular/router": "^4.2.4",
    "angularfire2": "^5.0.0-rc.4",
    "firebase": "4.8.0",
    "core-js": "^2.4.1",
    "rxjs": "^5.4.2",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "1.4.2",
    "@angular/compiler-cli": "^4.2.4",
    "@angular/language-service": "^4.2.4",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.1.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.3.2",
    "typescript": "~2.3.3"
  }
}

### How to reproduce these conditions

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**

**Steps to set up and reproduce**

when add firebase console to packege
and ng serve throw such error like in title 

ERROR in Error: Metadata version mismatch for module C:/Users/n1k1t/Desktop/Bilink/node_modules/angularfire2/index.d.ts, found version 4, expected 3, resolving symbol AppModule in C:/Users/n1k1t/Desktop/Bilink/src/app/app.module.ts, resolving symbol AppModule in C:/Users/n1k1t/Desktop/Bilink/src/app/app.module.ts, resolving symbol AppModule in C:/Users/n1k1t/Desktop/Bilink/src/app/app.module.ts
    at Error (native)
    at syntaxError (C:\Users\n1k1t\Desktop\Bilink\node_modules\@angular\compiler\bundles\compiler.umd.js:1729:34)
    at simplifyInContext (C:\Users\n1k1t\Desktop\Bilink\node_modules\@angular\compiler\bundles\compiler.umd.js:24979:23)
    at StaticReflector.simplify (C:\Users\n1k1t\Desktop\Bilink\node_modules\@angular\compiler\bundles\compiler.umd.js:24991:13)
    at StaticReflector.annotations (C:\Users\n1k1t\Desktop\Bilink\node_modules\@angular\compiler\bundles\compiler.umd.js:24418:41)
    at _getNgModuleMetadata (C:\Users\n1k1t\Desktop\Bilink\node_modules\@angular\compiler-cli\src\ngtools_impl.js:138:31)
    at _extractLazyRoutesFromStaticModule (C:\Users\n1k1t\Desktop\Bilink\node_modules\@angular\compiler-cli\src\ngtools_impl.js:109:26)
    at Object.listLazyRoutesOfModule (C:\Users\n1k1t\Desktop\Bilink\node_modules\@angular\compiler-cli\src\ngtools_impl.js:53:22)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (C:\Users\n1k1t\Desktop\Bilink\node_modules\@angular\compiler-cli\src\ngtools_api.js:91:39)
    at AotPlugin._getLazyRoutesFromNgtools (C:\Users\n1k1t\Desktop\Bilink\node_modules\@ngtools\webpack\src\plugin.js:207:44)
    at _donePromise.Promise.resolve.then.then.then.then.then (C:\Users\n1k1t\Desktop\Bilink\node_modules\@ngtools\webpack\src\plugin.js:443:24)
    at process._tickCallback (internal/process/next_tick.js:103:7)
webpack: Failed to compile.

**Comment by kigh143** [comment]
I think the release candidate has not been changed yet but there is a solution here.
Qhttps://stackoverflow.com/questions/47362366/error-in-error-metadata-version-mismatch-for-module-node-modules-angularfire/47455028#47455028

**Comment by kigh143** [comment]
https://stackoverflow.com/questions/47362366/error-in-error-metadata-version-mismatch-for-module-node-modules-angularfire/47455028#47455028

**Comment by Upskxkit** [comment]
Thanks, i'm gonna look it

**Comment by syncreticudon** [comment]
Getting this error with:
"angularfire2": "^5.0.0-rc.10",
"firebase": "^5.0.4",
