### ISSUE TITLE
angularfire2 is not able to find firestore.js when project is loaded

### ISSUE THREAD

**Issue by mrugesh008** [angular/angularfire2#1421]
My system.config.js is as shown below:

`(function(global) {
    System.config({
        paths: {
            // paths serve as alias
            'npm:': 'node_modules/'
        },
        // map tells the System loader where to look for things
        map: {
            // our app is within the app folder
            'app': 'app',

            // angular bundles
            '@angular/animations': 'npm:@angular/animations/bundles/animations.umd.js',
            '@angular/animations/browser': 'npm:@angular/animations/bundles/animations-browser.umd.js',
            '@angular/core': 'npm:@angular/core/bundles/core.umd.js',
            '@angular/common': 'npm:@angular/common/bundles/common.umd.js',
            '@angular/compiler': 'npm:@angular/compiler/bundles/compiler.umd.js',
            '@angular/platform-browser': 'npm:@angular/platform-browser/bundles/platform-browser.umd.js',
            '@angular/platform-browser/animations': 'npm:@angular/platform-browser/bundles/platform-browser-animations.umd.js',
            '@angular/platform-browser-dynamic': 'npm:@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',
            '@angular/http': 'npm:@angular/http/bundles/http.umd.js',
            '@angular/router': 'npm:@angular/router/bundles/router.umd.js',
            '@angular/router/upgrade': 'npm:@angular/router/bundles/router-upgrade.umd.js',
            '@angular/forms': 'npm:@angular/forms/bundles/forms.umd.js',
            '@angular/upgrade': 'npm:@angular/upgrade/bundles/upgrade.umd.js',
            '@angular/upgrade/static': 'npm:@angular/upgrade/bundles/upgrade-static.umd.js',
            '@angular/material': 'npm:@angular/material/bundles/material.umd.js',
            '@angular/cdk': 'npm:@angular/cdk/bundles/cdk.umd.js',
            '@angular/cdk/a11y': 'npm:@angular/cdk/bundles/cdk-a11y.umd.js',
            '@angular/cdk/bidi': 'npm:@angular/cdk/bundles/cdk-bidi.umd.js',
            '@angular/cdk/coercion': 'npm:@angular/cdk/bundles/cdk-coercion.umd.js',
            '@angular/cdk/collections': 'npm:@angular/cdk/bundles/cdk-collections.umd.js',
            '@angular/cdk/keycodes': 'npm:@angular/cdk/bundles/cdk-keycodes.umd.js',
            '@angular/cdk/observers': 'npm:@angular/cdk/bundles/cdk-observers.umd.js',
            '@angular/cdk/overlay': 'npm:@angular/cdk/bundles/cdk-overlay.umd.js',
            '@angular/cdk/platform': 'npm:@angular/cdk/bundles/cdk-platform.umd.js',
            '@angular/cdk/portal': 'npm:@angular/cdk/bundles/cdk-portal.umd.js',
            '@angular/cdk/rxjs': 'npm:@angular/cdk/bundles/cdk-rxjs.umd.js',
            '@angular/cdk/scrolling': 'npm:@angular/cdk/bundles/cdk-scrolling.umd.js',
            '@angular/cdk/stepper': 'npm:@angular/cdk/bundles/cdk-stepper.umd.js',
            '@angular/cdk/table': 'npm:@angular/cdk/bundles/cdk-table.umd.js',
            'angular2-social-login': 'node_modules/angular2-social-login/dist/bundles/angular2-social-login.min.js',
            'ngx-webstorage': 'node_modules/ngx-webstorage/bundles/core.umd.js',
            // other libraries
            'rxjs': 'npm:rxjs',
            'angular-in-memory-web-api': 'npm:angular-in-memory-web-api/bundles/in-memory-web-api.umd.js',
            '@ng-bootstrap/ng-bootstrap': 'node_modules/@ng-bootstrap/ng-bootstrap/bundles/ng-bootstrap.js',
            'lodash': 'node_modules/lodash/lodash.js',
            'angularfire2': 'node_modules/angularfire2',
            'firebase': 'npm:firebase'
        },
        // packages tells the System loader how to load when no filename and/or no extension
        packages: {
            app: {
                main: './main.js',
                defaultExtension: 'js',
                meta: {
                    './*.js': {
                        loader: 'systemjs-angular-loader.js'
                    }
                }
            },
            rxjs: {
                defaultExtension: 'js'
            },
            angularfire2:{
                main: './bundles/firestore.umd.js',
                defaultExtension: 'js'
            },
            firebase: { defaultExtension: 'js', main: './firebase.js' },
        }
    });
})(this);`

The moment I load my project it gives me the following error:

`HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).
(XHR)GET - http://localhost:3000/node_modules/firebase/firestore.js`

`[object Error]: {description: "(SystemJS) XHR error (404 Not Found) loading http://localhost:3000/node_modules/firebase/firestore.js Error: XHR error (404 Not Found) loading http://localhost:3000/node_modules/firebase/firestore.js at wrapFn (http://localhost:3000/node_modules/zone.js/dist/zone.js:1166:5) at ZoneDelegate.prototype.invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:423:13) at Zone.prototype.runTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:192:21) at ZoneTask.invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:499:17) at invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:1540:9) at globalZoneAwareCallback (http://localhost:3000/node_modules/zone.js/dist/zone.js:1566:17) Error loading http://localhost:3000/node_modules/firebase/firestore.js as "firebase/firestore" from http://localhost:3000/node_modules/angularfire2/bundles/firestore.umd.js", message: "(SystemJS) XHR error (404 Not Found) loading http://localhost:3000/node_modules/firebase/firestore.js Error: XHR error (404 Not Found) loading http://localhost:3000/node_modules/firebase/firestore.js at wrapFn (http://localhost:3000/node_modules/zone.js/dist/zone.js:1166:5) at ZoneDelegate.prototype.invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:423:13) at Zone.prototype.runTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:192:21) at ZoneTask.invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:499:17) at invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:1540:9) at globalZoneAwareCallback (http://localhost:3000/node_modules/zone.js/dist/zone.js:1566:17) Error loading http://localhost:3000/node_modules/firebase/firestore.js as "firebase/firestore" from http://localhost:3000/node_modules/angularfire2/bundles/firestore.umd.js", originalErr: Object, stack: "(SystemJS) XHR error (404 Not Found) loading http://localhost:3000/node_modules/firebase/firestore.js Error: XHR error (404 Not Found) loading http://localhost:3000/node_modules/firebase/firestore.js at wrapFn (http://localhost:3000/node_modules/zone.js/dist/zone.js:1166:5) at ZoneDelegate.prototype.invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:423:13) at Zone.prototype.runTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:192:21) at ZoneTask.invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:499:17) at invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:1540:9) at globalZoneAwareCallback (http://localhost:3000/node_modules/zone.js/dist/zone.js:1566:17) Error loading http://localhost:3000/node_modules/firebase/firestore.js as "firebase/firestore" from http://localhost:3000/node_modules/angularfire2/bundles/firestore.umd.js"}`

I am using "angularfire2": "^5.0.0-rc.4",  "firebase": "^4.8.0", for my project. Is there any bug in the package itself or I am not inserting it propely?

**Comment by mrugesh008** [comment]
I tried your way. But now it is giving me the error as shown below:


`HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).
(XHR)GET - http://localhost:3000/node_modules/firebase/app/app.js`



My systemjs.config.js is 

`(function(global) {
    System.config({
        paths: {
            // paths serve as alias
            'npm:': 'node_modules/'
        },
        // map tells the System loader where to look for things
        map: {
            // our app is within the app folder
            'app': 'app',
            ......
            ......
            'angularfire2': 'node_modules/angularfire2',
            'firebase': 'npm:firebase/app'
        },
        // packages tells the System loader how to load when no filename and/or no extension
        packages: {
            app: {
                main: './main.js',
                defaultExtension: 'js',
                meta: {
                    './*.js': {
                        loader: 'systemjs-angular-loader.js'
                    }
                }
            },
            rxjs: {
                defaultExtension: 'js'
            },
            angularfire2:{
                main: './bundles/core.umd.js',
                defaultExtension: 'js'
            },
            firebase: { defaultExtension: 'js',
                main: './firebase.js' },
        }
    });
})(this);`

**Comment by AnthonyNahas** [comment]
@mrugesh008 For my [ngx-auth-firebaseui](https://www.npmjs.com/package/ngx-auth-firebaseui) package, I am using the following systemJS configuration that support

- angular
- angularfire2 (incl. auth, firestore...)
- firebase

and it's working like a Mercedes ;) 🥇 

so if you adapt your systemJS config like mine, I believe that you app will work better... 💯 

```js
'use strict';
/**
 * System configuration for Angular samples
 * Adjust as necessary for your application needs.
 */
(function () {
    System.config({

        paths: {
            // paths serve as alias
            'npm:': '../node_modules/',
            "tslib": "node_modules/tslib/tslib.js"
        },
        // map tells the System loader where to look for things
        map: {
            // our app is within the app folder
            app: 'app',

            // angular bundles
            '@angular/core': 'npm:@angular/core/bundles/core.umd.js',
            '@angular/common': 'npm:@angular/common/bundles/common.umd.js',
            '@angular/common/http': 'npm:@angular/common/bundles/common-http.umd.js',
            '@angular/compiler': 'npm:@angular/compiler/bundles/compiler.umd.js',
            '@angular/platform-browser': 'npm:@angular/platform-browser/bundles/platform-browser.umd.js',
            '@angular/platform-browser/animations': 'npm:@angular/platform-browser/bundles/platform-browser-animations.umd.js',
            '@angular/platform-browser-dynamic': 'npm:@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',
            '@angular/http': 'npm:@angular/http/bundles/http.umd.js',
            '@angular/router': 'npm:@angular/router/bundles/router.umd.js',
            '@angular/forms': 'npm:@angular/forms/bundles/forms.umd.js',
            '@angular/animations': 'npm:@angular/animations/bundles/animations.umd.js',
            '@angular/animations/browser': 'npm:@angular/animations/bundles/animations-browser.umd.js',
            '@angular/material': 'npm:@angular/material/bundles/material.umd.js',
            '@angular/cdk': 'npm:@angular/cdk/bundles/cdk.umd.js',
            '@angular/cdk/a11y': 'npm:/@angular/cdk/bundles/cdk-a11y.umd.js',
            '@angular/cdk/accordion': 'npm:/@angular/cdk/bundles/cdk-accordion.umd.js',
            '@angular/cdk/bidi': 'npm:/@angular/cdk/bundles/cdk-bidi.umd.js',
            '@angular/cdk/observers': 'npm:/@angular/cdk/bundles/cdk-observers.umd.js',
            '@angular/cdk/overlay': 'npm:/@angular/cdk/bundles/cdk-overlay.umd.js',
            '@angular/cdk/portal': 'npm:/@angular/cdk/bundles/cdk-portal.umd.js',
            '@angular/cdk/scrolling': 'npm:/@angular/cdk/bundles/cdk-scrolling.umd.js',
            '@angular/cdk/platform': 'npm:/@angular/cdk/bundles/cdk-platform.umd.js',
            '@angular/cdk/keycodes': 'npm:/@angular/cdk/bundles/cdk-keycodes.umd.js',
            '@angular/cdk/coercion': 'npm:/@angular/cdk/bundles/cdk-coercion.umd.js',
            '@angular/cdk/collections': 'npm:/@angular/cdk/bundles/cdk-collections.umd.js',
            '@angular/cdk/layout': 'npm:/@angular/cdk/bundles/cdk-layout.umd.js',
            '@angular/cdk/rxjs': 'npm:/@angular/cdk/bundles/cdk-rxjs.umd.js',
            '@angular/cdk/stepper': 'npm:/@angular/cdk/bundles/cdk-stepper.umd.js',
            '@angular/cdk/table': 'npm:/@angular/cdk/bundles/cdk-table.umd.js',
            '@angular/flex-layout': 'npm:@angular/flex-layout/bundles/flex-layout.umd.js',

            // other libraries
            rxjs: 'npm:rxjs',
            'angular-in-memory-web-api': 'npm:angular-in-memory-web-api/bundles/in-memory-web-api.umd.js',
            'firebase': 'npm:firebase',
            'firebase/app': 'npm:firebase/app',
            'firebase/auth': 'npm:firebase/auth',
            'firebase/firestore': 'npm:firebase/firestore',
            '@firebase/app': 'npm:@firebase/app/dist/cjs',
            '@firebase/auth': 'npm:@firebase/auth/dist',
            '@firebase/firestore': 'npm:@firebase/firestore/dist/cjs',
            '@firebase/polyfill': 'npm:@firebase/polyfill/dist/cjs',
            '@firebase/util': 'npm:@firebase/util/dist/cjs',
            '@firebase/webchannel-wrapper': 'npm:@firebase/webchannel-wrapper/dist',
            'promise-polyfill': 'npm:promise-polyfill',
            // Firebase libraries
            'angularfire2': 'npm:angularfire2/bundles/core.umd.js',
            'angularfire2/database': 'npm:angularfire2/bundles/database.umd.js',
            'angularfire2/auth': 'npm:angularfire2/bundles/auth.umd.js',
            'angularfire2/firestore': 'npm:angularfire2/bundles/firestore.umd.js',
            'ngx-auth-firebaseui': '../dist'
        },
        // packages tells the System loader how to load when no filename and/or no extension
        packages: {
            app: {
                defaultExtension: 'js',
                meta: {
                    './*.js': {
                        loader: 'systemjs-angular-loader.js'
                    }
                }
            },
            rxjs: {
                defaultExtension: 'js'
            },
            'firebase': {defaultExtension: 'js', main: './firebase.js'},
            'firebase/app': {defaultExtension: 'js', main: './index.js'},
            'firebase/auth': {defaultExtension: 'js', main: './index.js'},
            'firebase/firestore': {defaultExtension: 'js', main: './index.js'},
            '@firebase/app': {defaultExtension: 'js', main: './index.js'},
            '@firebase/auth': {defaultExtension: 'js', main: './auth.js'},
            '@firebase/firestore': {defaultExtension: 'js', main: './index.js'},
            '@firebase/polyfill': {defaultExtension: 'js', main: './index.js'},
            '@firebase/util': {defaultExtension: 'js', main: './index.js'},
            '@firebase/webchannel-wrapper': {defaultExtension: 'js', main: './index.js'},
            'promise-polyfill': {defaultExtension: 'js', main: './promise.js'},
            'ngx-auth-firebaseui': {
                main: 'ngx-auth-firebaseui.umd.js',
                defaultExtension: 'js'
            }
        },
    });
})(this);

```
