### ISSUE TITLE
Got a Firebase auth error, please

### ISSUE THREAD

**Issue by noor07** [angular/angularfire2#1451]
Runtime Error
Network Error
Stack

Error: Network Error
    at http://localhost:8100/build/vendor.js:81622:411
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:15660)
    at r.runTask (http://localhost:8100/build/polyfills.js:3:10834)
    at e.invokeTask (http://localhost:8100/build/polyfills.js:3:16794)
    at i.isUsingGlobalCallback.invoke (http://localhost:8100/build/polyfills.js:3:16682)
    at n (http://localhost:8100/build/polyfills.js:3:61)

My Version Info :- 

Ionic Framework: 3.9.2
Ionic App Scripts: 3.1.6
Angular Core: 5.0.3
Angular Compiler CLI: 5.0.3
Node: 8.9.4
OS Platform: Windows 10
Navigator Platform: Win32
User Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 10_3 like Mac OS X) AppleWebKit/602.1.50 (KHTML, like Gecko) CriOS/56.0.2924.75 Mobile/14E5239e Safari/602.1

**Comment by davideast** [comment]
Hi @noor07! Try using stackoverflow for these kind of questions. It is always helpful when your provide a reproducible error in a repo or stackblitz app.
