### ISSUE TITLE
Error: Uncaught (in promise): TypeError: Function expected TypeError: Function expected

### ISSUE THREAD

**Issue by arissofan** [angular/angularfire2#1702]
### Version info

**Angular: 5.2.10**

**Firebase: 5.0.4**

**AngularFire: 5.0.0-rc.10**

**Other (e.g. Ionic/Cordova, Node, browser, operating system):
    @ionic/app-scripts : 3.1.9
    Cordova Platforms  : android 7.0.0
    Ionic Framework    : ionic-angular 3.9.2**

### How to reproduce these conditions

**i try follow this one javebratt.com/crud-ionic-firestore/**

### Debug output

** Error: Uncaught (in promise): TypeError: Function expected
TypeError: Function expected
   at Anonymous function (http://localhost:8100/build/vendor.js:64767:13)
   at t.prototype.invoke (http://localhost:8100/build/polyfills.js:3:14879)
   at r.prototype.run (http://localhost:8100/build/polyfills.js:3:10117)
   at NgZone.prototype.runOutsideAngular (http://localhost:8100/build/vendor.js:5393:9)
   at AngularFirestore (http://localhost:8100/build/vendor.js:64766:9)
   at _createClass (http://localhost:8100/build/vendor.js:11628:13)
   at _createProviderInstance$1 (http://localhost:8100/build/vendor.js:11592:13)
   at resolveNgModuleDep (http://localhost:8100/build/vendor.js:11576:13)
   at _createClass (http://localhost:8100/build/vendor.js:11618:13)
   at _createProviderInstance$1 (http://localhost:8100/build/vendor.js:11592:13)
   at c (http://localhost:8100/build/polyfills.js:3:19746)
   at Anonymous function (http://localhost:8100/build/polyfills.js:3:19174)
   at NavControllerBase.prototype._fireError (http://localhost:8100/build/vendor.js:53602:13)
   at NavControllerBase.prototype._failed (http://localhost:8100/build/vendor.js:53595:9)
   at Anonymous function (http://localhost:8100/build/vendor.js:53642:46)
   at t.prototype.invoke (http://localhost:8100/build/polyfills.js:3:14879)
   at onInvoke (http://localhost:8100/build/vendor.js:5445:17)
   at t.prototype.invoke (http://localhost:8100/build/polyfills.js:3:14879)
   at r.prototype.run (http://localhost:8100/build/polyfills.js:3:10117)
   at Anonymous function (http://localhost:8100/build/polyfills.js:3:20233)
**

**Comment by arissofan** [comment]
It's just compatibility issues.. downgrading the angularfire2 version and that's all

**Comment by Ntshuxekani** [comment]
Error: Uncaught (in promise): TypeError: Function expected
TypeError: Function expected
