### ISSUE TITLE
Metadata version mismatch for module for prod

### ISSUE THREAD

**Issue by Vatsov** [angular/angularfire2#1753]
### Version info

**Angular:** 4.1.3

**Ionic-Angular:** 3.6.1

**Firebase:** 5.2.0

**AngularFire:** 5.0.0-rc.11

with Firebase: 4.9.0 and AngularFire: 5.0.0-rc.6 was the same

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 6.3.0 browser 5.0.1 ios 4.5.4
    Ionic Framework    : ionic-angular 3.6.1

System:

    Android SDK Tools : 25.2.3
    Node              : v8.9.0
    npm               : 5.5.1 
    OS                : macOS High Sierra

**Steps to set up and reproduce**

It's work fine with:
$ ionic cordova build ios 

The error is appear with:
$ ionic cordova build ios --prod

### Expected behavior

To be build without errors

### Actual behavior

The error is:

Error: Metadata version mismatch for module /Users/vatsov/dev/bebeshor/node_modules/angularfire2/index.d.ts, found version 4, expected 3
    at StaticSymbolResolver.getModuleMetadata (/Users/vatsov/dev/bebeshor/node_modules/@angular/compiler/bundles/compiler.umd.js:24474:34)
    at StaticSymbolResolver._createSymbolsOf (/Users/vatsov/dev/bebeshor/node_modules/@angular/compiler/bundles/compiler.umd.js:24260:46)
    at StaticSymbolResolver.getSymbolsOf (/Users/vatsov/dev/bebeshor/node_modules/@angular/compiler/bundles/compiler.umd.js:24241:14)
    at /Users/vatsov/dev/bebeshor/node_modules/@angular/compiler/bundles/compiler.umd.js:23023:30
    at Array.forEach (<anonymous>)
    at extractProgramSymbols (/Users/vatsov/dev/bebeshor/node_modules/@angular/compiler/bundles/compiler.umd.js:23022:79)
    at AotCompiler.compileAll (/Users/vatsov/dev/bebeshor/node_modules/@angular/compiler/bundles/compiler.umd.js:22720:47)
    at CodeGenerator.codegen (/Users/vatsov/dev/bebeshor/node_modules/@angular/compiler-cli/src/codegen.js:30:14)
    at Function.NgTools_InternalApi_NG_2.codeGen (/Users/vatsov/dev/bebeshor/node_modules/@angular/compiler-cli/src/ngtools_api.js:61:30)
    at /Users/vatsov/dev/bebeshor/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:182:73

**Comment by hiepxanh** [comment]
can you provide a minimum repository?

**Comment by jamesdaniels** [comment]
This is due to the recent RCs requiring Angular 4.
