### ISSUE TITLE
When i launch angular ssr in nginx, I get this error. If there any solution for this?

### ISSUE THREAD

**Issue by umeshblader3** [angular/angularfire2#1772]
Node server listening http://localhost:4000
ERROR TypeError: zone.runOutsideAngular is not a function
    at new AngularFirestore (/home/ubuntu/app_frontend/ecosoftlk/dist2/node_modules/angularfire2/bundles/firestore.umd.js:156:31)
    at _createClass (/home/ubuntu/app_frontend/ecosoftlk/dist2/node_modules/@angular/core/bundles/core.umd.js:10981:20)
    at _createProviderInstance$1 (/home/ubuntu/app_frontend/ecosoftlk/dist2/node_modules/@angular/core/bundles/core.umd.js:10945:26)
    at resolveNgModuleDep (/home/ubuntu/app_frontend/ecosoftlk/dist2/node_modules/@angular/core/bundles/core.umd.js:10930:17)
    at _createClass (/home/ubuntu/app_frontend/ecosoftlk/dist2/node_modules/@angular/core/bundles/core.umd.js:10975:29)
    at _createProviderInstance$1 (/home/ubuntu/app_frontend/ecosoftlk/dist2/node_modules/@angular/core/bundles/core.umd.js:10945:26)
    at resolveNgModuleDep (/home/ubuntu/app_frontend/ecosoftlk/dist2/node_modules/@angular/core/bundles/core.umd.js:10930:17)
    at NgModuleRef_.get (/home/ubuntu/app_frontend/ecosoftlk/dist2/node_modules/@angular/core/bundles/core.umd.js:12167:16)
    at resolveDep (/home/ubuntu/app_frontend/ecosoftlk/dist2/node_modules/@angular/core/bundles/core.umd.js:12657:45)
    at createClass (/home/ubuntu/app_frontend/ecosoftlk/dist2/node_modules/@angular/core/bundles/core.umd.js:12519:29)
Unhandled Promise rejection: zone.runOutsideAngular is not a function ; Zone: <root> ; Task: Promise.then ; Value: TypeError: zone.runOutsideAngular is not a function
    at new AngularFirestore (/home/ubuntu/app_frontend/ecosoftlk/dist2/node_modules/angularfire2/bundles/firestore.umd.js:156:31)
    at _createClass (/home/ubuntu/app_frontend/ecosoftlk/dist2/node_modules/@angular/core/bundles/core.umd.js:10981:20)
    at _createProviderInstance$1 (/home/ubuntu/app_frontend/ecosoftlk/dist2/node_modules/@angular/core/bundles/core.umd.js:10945:26)
    at resolveNgModuleDep (/home/ubuntu/app_frontend/ecosoftlk/dist2/node_modules/@angular/core/bundles/core.umd.js:10930:17)
    at _createClass (/home/ubuntu/app_frontend/ecosoftlk/dist2/node_modules/@angular/core/bundles/core.umd.js:10975:29)
    at _createProviderInstance$1 (/home/ubuntu/app_frontend/ecosoftlk/dist2/node_modules/@angular/core/bundles/core.umd.js:10945:26)
    at resolveNgModuleDep (/home/ubuntu/app_frontend/ecosoftlk/dist2/node_modules/@angular/core/bundles/core.umd.js:10930:17)
    at NgModuleRef_.get (/home/ubuntu/app_frontend/ecosoftlk/dist2/node_modules/@angular/core/bundles/core.umd.js:12167:16)
    at resolveDep (/home/ubuntu/app_frontend/ecosoftlk/dist2/node_modules/@angular/core/bundles/core.umd.js:12657:45)
    at createClass (/home/ubuntu/app_frontend/ecosoftlk/dist2/node_modules/@angular/core/bundles/core.umd.js:12519:29) TypeError: zone.runOutsideAngular is not a function
    at new AngularFirestore (/home/ubuntu/app_frontend/ecosoftlk/dist2/node_modules/angularfire2/bundles/firestore.umd.js:156:31)
    at _createClass (/home/ubuntu/app_frontend/ecosoftlk/dist2/node_modules/@angular/core/bundles/core.umd.js:10981:20)
    at _createProviderInstance$1 (/home/ubuntu/app_frontend/ecosoftlk/dist2/node_modules/@angular/core/bundles/core.umd.js:10945:26)
    at resolveNgModuleDep (/home/ubuntu/app_frontend/ecosoftlk/dist2/node_modules/@angular/core/bundles/core.umd.js:10930:17)
    at _createClass (/home/ubuntu/app_frontend/ecosoftlk/dist2/node_modules/@angular/core/bundles/core.umd.js:10975:29)
    at _createProviderInstance$1 (/home/ubuntu/app_frontend/ecosoftlk/dist2/node_modules/@angular/core/bundles/core.umd.js:10945:26)
    at resolveNgModuleDep (/home/ubuntu/app_frontend/ecosoftlk/dist2/node_modules/@angular/core/bundles/core.umd.js:10930:17)
    at NgModuleRef_.get (/home/ubuntu/app_frontend/ecosoftlk/dist2/node_modules/@angular/core/bundles/core.umd.js:12167:16)
    at resolveDep (/home/ubuntu/app_frontend/ecosoftlk/dist2/node_modules/@angular/core/bundles/core.umd.js:12657:45)
    at createClass (/home/ubuntu/app_frontend/ecosoftlk/dist2/node_modules/@angular/core/bundles/core.umd.js:12519:29)
ERROR TypeError: zone.runOutsideAngular is not a function
    at new AngularFirestore (/home/ubuntu/app_frontend/ecosoftlk/dist2/node_modules/angularfire2/bundles/firestore.umd.js:156:31)
    at _createClass (/home/ubuntu/app_frontend/ecosoftlk/dist2/node_modules/@angular/core/bundles/core.umd.js:10981:20)
    at _createProviderInstance$1 (/home/ubuntu/app_frontend/ecosoftlk/dist2/node_modules/@angular/core/bundles/core.umd.js:10945:26)
    at resolveNgModuleDep (/home/ubuntu/app_frontend/ecosoftlk/dist2/node_modules/@angular/core/bundles/core.umd.js:10930:17)
    at _createClass (/home/ubuntu/app_frontend/ecosoftlk/dist2/node_modules/@angular/core/bundles/core.umd.js:10975:29)
    at _createProviderInstance$1 (/home/ubuntu/app_frontend/ecosoftlk/dist2/node_modules/@angular/core/bundles/core.umd.js:10945:26)
    at resolveNgModuleDep (/home/ubuntu/app_frontend/ecosoftlk/dist2/node_modules/@angular/core/bundles/core.umd.js:10930:17)
    at NgModuleRef_.get (/home/ubuntu/app_frontend/ecosoftlk/dist2/node_modules/@angular/core/bundles/core.umd.js:12167:16)
    at resolveDep (/home/ubuntu/app_frontend/ecosoftlk/dist2/node_modules/@angular/core/bundles/core.umd.js:12657:45)
    at createClass (/home/ubuntu/app_frontend/ecosoftlk/dist2/node_modules/@angular/core/bundles/core.umd.js:12519:29)
Unhandled Promise rejection: zone.runOutsideAngular is not a function ; Zone: <root> ; Task: Promise.then ; Value: TypeError: zone.runOutsideAngular is not a function
    at new AngularFirestore (/home/ubuntu/app_frontend/ecosoftlk/dist2/node_modules/angularfire2/bundles/firestore.umd.js:156:31)
    at _createClass (/home/ubuntu/app_frontend/ecosoftlk/dist2/node_modules/@angular/core/bundles/core.umd.js:10981:20)
    at _createProviderInstance$1 (/home/ubuntu/app_frontend/ecosoftlk/dist2/node_modules/@angular/core/bundles/core.umd.js:10945:26)
    at resolveNgModuleDep (/home/ubuntu/app_frontend/ecosoftlk/dist2/node_modules/@angular/core/bundles/core.umd.js:10930:17)
    at _createClass (/home/ubuntu/app_frontend/ecosoftlk/dist2/node_modules/@angular/core/bundles/core.umd.js:10975:29)
    at _createProviderInstance$1 (/home/ubuntu/app_frontend/ecosoftlk/dist2/node_modules/@angular/core/bundles/core.umd.js:10945:26)
    at resolveNgModuleDep (/home/ubuntu/app_frontend/ecosoftlk/dist2/node_modules/@angular/core/bundles/core.umd.js:10930:17)
    at NgModuleRef_.get (/home/ubuntu/app_frontend/ecosoftlk/dist2/node_modules/@angular/core/bundles/core.umd.js:12167:16)
    at resolveDep (/home/ubuntu/app_frontend/ecosoftlk/dist2/node_modules/@angular/core/bundles/core.umd.js:12657:45)
    at createClass (/home/ubuntu/app_frontend/ecosoftlk/dist2/node_modules/@angular/core/bundles/core.umd.js:12519:29) TypeError: zone.runOutsideAngular is not a function
    at new AngularFirestore (/home/ubuntu/app_frontend/ecosoftlk/dist2/node_modules/angularfire2/bundles/firestore.umd.js:156:31)
    at _createClass (/home/ubuntu/app_frontend/ecosoftlk/dist2/node_modules/@angular/core/bundles/core.umd.js:10981:20)
    at _createProviderInstance$1 (/home/ubuntu/app_frontend/ecosoftlk/dist2/node_modules/@angular/core/bundles/core.umd.js:10945:26)
    at resolveNgModuleDep (/home/ubuntu/app_frontend/ecosoftlk/dist2/node_modules/@angular/core/bundles/core.umd.js:10930:17)
    at _createClass (/home/ubuntu/app_frontend/ecosoftlk/dist2/node_modules/@angular/core/bundles/core.umd.js:10975:29)
    at _createProviderInstance$1 (/home/ubuntu/app_frontend/ecosoftlk/dist2/node_modules/@angular/core/bundles/core.umd.js:10945:26)
    at resolveNgModuleDep (/home/ubuntu/app_frontend/ecosoftlk/dist2/node_modules/@angular/core/bundles/core.umd.js:10930:17)
    at NgModuleRef_.get (/home/ubuntu/app_frontend/ecosoftlk/dist2/node_modules/@angular/core/bundles/core.umd.js:12167:16)
    at resolveDep (/home/ubuntu/app_frontend/ecosoftlk/dist2/node_modules/@angular/core/bundles/core.umd.js:12657:45)
    at createClass (/home/ubuntu/app_frontend/ecosoftlk/dist2/node_modules/@angular/core/bundles/core.umd.js:12519:29)

**Comment by hiepxanh** [comment]
hello, can you follow the issue template. how can I reproduce your error? which version of firebase are you using?  can you provide a minimum of repository that we can review it?
