### ISSUE TITLE
ERROR TypeError: Cannot read property 'filter' of undefined in 5.0.0-rc.11

### ISSUE THREAD

**Issue by umeshblader3** [angular/angularfire2#1784]
**Still the error comes in 5.0.0-rc.11 **
ERROR TypeError: Cannot read property 'filter' of undefined
    at _firebaseAppFactory (/Users/umeshblader/Projects/front-end/ecosoftlk-new/dist/server.js:58665:41)
    at /Users/umeshblader/Projects/front-end/ecosoftlk-new/dist/server.js:98786:66
    at ZoneDelegate.module.exports.ZoneDelegate.invoke (/Users/umeshblader/Projects/front-end/ecosoftlk-new/dist/server.js:156663:26)
    at Zone.module.exports.Zone.run (/Users/umeshblader/Projects/front-end/ecosoftlk-new/dist/server.js:156413:43)
    at NgZone.module.exports.NgZone.runOutsideAngular (/Users/umeshblader/Projects/front-end/ecosoftlk-new/dist/server.js:4071:28)
    at new AngularFirestore (/Users/umeshblader/Projects/front-end/ecosoftlk-new/dist/server.js:98785:31)
    at _createClass (/Users/umeshblader/Projects/front-end/ecosoftlk-new/dist/server.js:8568:20)
    at _createProviderInstance (/Users/umeshblader/Projects/front-end/ecosoftlk-new/dist/server.js:8530:26)
    at resolveNgModuleDep (/Users/umeshblader/Projects/front-end/ecosoftlk-new/dist/server.js:8493:21)
    at _createClass (/Users/umeshblader/Projects/front-end/ecosoftlk-new/dist/server.js:8562:29)
TypeError: Cannot read property 'filter' of undefined
    at _firebaseAppFactory (/Users/umeshblader/Projects/front-end/ecosoftlk-new/dist/server.js:58665:41)
    at /Users/umeshblader/Projects/front-end/ecosoftlk-new/dist/server.js:98786:66
    at ZoneDelegate.module.exports.ZoneDelegate.invoke (/Users/umeshblader/Projects/front-end/ecosoftlk-new/dist/server.js:156663:26)
    at Zone.module.exports.Zone.run (/Users/umeshblader/Projects/front-end/ecosoftlk-new/dist/server.js:156413:43)
    at NgZone.module.exports.NgZone.runOutsideAngular (/Users/umeshblader/Projects/front-end/ecosoftlk-new/dist/server.js:4071:28)
    at new AngularFirestore (/Users/umeshblader/Projects/front-end/ecosoftlk-new/dist/server.js:98785:31)
    at _createClass (/Users/umeshblader/Projects/front-end/ecosoftlk-new/dist/server.js:8568:20)
    at _createProviderInstance (/Users/umeshblader/Projects/front-end/ecosoftlk-new/dist/server.js:8530:26)
    at resolveNgModuleDep (/Users/umeshblader/Projects/front-end/ecosoftlk-new/dist/server.js:8493:21)
    at _createClass (/Users/umeshblader/Projects/front-end/ecosoftlk-new/dist/server.js:8562

**Comment by davideast** [comment]
Please use the compat library or upgrade to RxJS 6.

**Comment by Kamshak** [comment]
Still get this no matter what the RxJS version is. When debugging the firebase it imports contains a "default" property. I suspect it is related to this: https://github.com/Microsoft/TypeScript/issues/2719

**Comment by Kamshak** [comment]
using the "module" entry in package.json in webpack resolve (esm)
