### ISSUE TITLE
Problem with Authentication , Facebook provider

### ISSUE THREAD

**Issue by Ahrimaan** [angular/angularfire2#288]
Hi Team,

ive started with your Tutorial to connect to Firebase.

my main.ts 

```
import { bootstrap } from '@angular/platform-browser-dynamic';
import { HTTP_PROVIDERS } from '@angular/http';
import { enableProdMode } from '@angular/core';
import { AppComponent, environment } from './app/';
import { FIREBASE_PROVIDERS, 
  defaultFirebase, 
  AngularFire, 
  AuthMethods, 
  AuthProviders, 
  firebaseAuthConfig } from 'angularfire2';

if (environment.production) {
  enableProdMode();
}

bootstrap(AppComponent,[
  HTTP_PROVIDERS,
  defaultFirebase({
    apiKey: "MYKEY",
    authDomain: "MYURL.firebaseapp.com",
    databaseURL: "https://MYURL.firebaseio.com",
    storageBucket: "MYURL.appspot.com",
  }),
  firebaseAuthConfig({
    provider: AuthProviders.Password,
    method: AuthMethods.Popup
  }) 
]).then(success => console.log('appCompnent Bootstrapped'), error => console.log(error));
```

But when i want to load my App, i get following error:

```
> zone.js:461 Unhandled Promise rejection: TypeError: Cannot read property 'FacebookAuthProvider' of undefined
> 	    at Object.eval (http://localhost:4200/vendor/angularfire2/providers/firebase_sdk_auth_backend.js:24:43)
> 	    at eval (http://localhost:4200/vendor/angularfire2/providers/firebase_sdk_auth_backend.js:108:4)
> 	    at eval (http://localhost:4200/vendor/angularfire2/providers/firebase_sdk_auth_backend.js:109:3)
> 	    at Object.eval (http://localhost:4200/vendor/angularfire2/angularfire2.js:33:35)
> 	Evaluating http://localhost:4200/vendor/angularfire2/providers/firebase_sdk_auth_backend.js
> 	Evaluating http://localhost:4200/vendor/angularfire2/angularfire2.js
> 	Evaluating http://localhost:4200/main.js
> 	Error loading http://localhost:4200/main.js ; Zone: <root> ; Task: Promise.then ; Value: Error: TypeError: Cannot read property 'FacebookAuthProvider' of undefined(…)
```

**Comment by Ahrimaan** [comment]
Configuration mess in my soluition....
