### ISSUE TITLE
Can't resolve all parameters for AngularFireAuth: (AuthBackend, ?, ?)

### ISSUE THREAD

**Issue by mafzst** [angular/angularfire2#487]
I'm trying to implements Firebase on my Ionic2 App (Angular2)

I followed the installation guide but I encountered an error : 
```
browser_adapter.js:84 Error: Can't resolve all parameters for AngularFireAuth: (AuthBackend, ?, ?).
    at new BaseException (http://localhost:8100/build/js/app.bundle.js:2089:23)
    at CompileMetadataResolver.getDependenciesMetadata (http://localhost:8100/build/js/app.bundle.js:14488:19)
    at CompileMetadataResolver.getTypeMetadata (http://localhost:8100/build/js/app.bundle.js:14369:26)
    at http://localhost:8100/build/js/app.bundle.js:14523:30
    at Array.map (native)
    at CompileMetadataResolver.getProvidersMetadata (http://localhost:8100/build/js/app.bundle.js:14511:26)
    at http://localhost:8100/build/js/app.bundle.js:14514:30
    at Array.map (native)
    at CompileMetadataResolver.getProvidersMetadata (http://localhost:8100/build/js/app.bundle.js:14511:26)
    at http://localhost:8100/build/js/app.bundle.js:14514:30
``` 

I'm using ` beta.3` version for compatibility reasons

Here my `app.ts` : 
```
import {Component} from '@angular/core';
import {Platform, ionicBootstrap} from 'ionic-angular';
import {StatusBar} from 'ionic-native';
import {
  FIREBASE_PROVIDERS,
  defaultFirebase
} from 'angularfire2';
import {HomePage} from './pages/home/home';

let prodMode: boolean = !!window.hasOwnProperty('cordava');

@Component({
  template: '<ion-nav [root]="rootPage"></ion-nav>',
  providers: [
    FIREBASE_PROVIDERS,
    defaultFirebase({
      apiKey: "xxxxxxxxxxxxx",
      authDomain: "janari-xxxxx.firebaseapp.com",
      databaseURL: "https://janari-xxxxx.firebaseio.com",
      storageBucket: "janari-xxxxx.appspot.com",
    })
    // firebaseAuthConfig({
    //   provider: AuthProviders.Password,
    //   method: AuthMethods.Password
    // })
  ]
})
export class MyApp {

  private rootPage: any;

  constructor(private platform: Platform) {
    this.rootPage = HomePage;

    platform.ready().then(() => {
      // Okay, so the platform is ready and our plugins are available.
      // Here you can do any higher level native things you might need.
      StatusBar.styleDefault();
    });
  }
}

ionicBootstrap(MyApp, [], {prodMode: prodMode});
```

Thanks for your help :)

**Comment by davideast** [comment]
@mafzst You should be using `beta2`, which targets RC4. Can you give that a go and let me know what happens?

**Comment by mafzst** [comment]
@davideast Thanks for your reply!
I've tried it but `beta2` seems to require angular rc2 : 
```
npm WARN angularfire2@2.0.0-beta.2 requires a peer of @angular/core@2.0.0-rc.2 but none was installed.
npm WARN angularfire2@2.0.0-beta.2 requires a peer of @angular/platform-browser@2.0.0-rc.2 but none was installed.
npm WARN angularfire2@2.0.0-beta.2 requires a peer of @angular/common@2.0.0-rc.2 but none was installed.
npm WARN angularfire2@2.0.0-beta.2 requires a peer of @angular/compiler@2.0.0-rc.2 but none was installed.
npm WARN angularfire2@2.0.0-beta.2 requires a peer of @angular/platform-browser-dynamic@2.0.0-rc.2 but none was installed.
```

**Comment by davideast** [comment]
@mafzst Sorry, I meant to say`beta2` works with RC4. It targets RC2 but those peer dependency warnings are benign. 

Once Ionic upgrades to RC5/RC6 we'll have a compatible release for them.
