### ISSUE TITLE
Getting 404 GET /traceur

### ISSUE THREAD

**Issue by Klemen1337** [angular/angularfire2#530]
Anyone getting traceur not found error?

Cheers :beer:,
K

```
localhost/:17 Error: Error: XHR error (404 Not Found) loading http://localhost:3000/traceur
	    at XMLHttpRequest.wrapFn [as _onreadystatechange] (http://localhost:3000/node_modules/zone.js/dist/zone.js:636:29)
	    at ZoneDelegate.invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:225:37)
	    at Zone.runTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:125:47)
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:293:33)
	Error loading http://localhost:3000/traceur
	Error loading http://localhost:3000/node_modules/angularfire2/angularfire2.js as "angularfire2" from http://localhost:3000/app/app.module.js(anonymous function) @ localhost/:17
```

**Comment by jormaturkenburg** [comment]
I'm getting the same error.

**Comment by hllink** [comment]
same here

**Comment by Klemen1337** [comment]
I think it just needs to be updated for the final version.

**Comment by davideast** [comment]
Closing as it seems to work with the final version.

**Comment by ascreamingweas** [comment]
I'm getting a very similar error, would anyone mind telling me what they changed for the fix?

`Error: XHR error (404 Not Found) loading http://localhost:3000/traceur
	    at XMLHttpRequest.wrapFn [as _onreadystatechange] (http://localhost:3000/node_modules/zone.js/dist/zone.js:636:29)
	    at ZoneDelegate.invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:225:37)
	    at Zone.runTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:125:47)
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:293:33)
	Error loading http://localhost:3000/traceur
	Error loading http://localhost:3000/app/main.ts`

**Comment by satyabratasenapati** [comment]
I have the same issue .Please kindly help to solve

**Comment by Judahh** [comment]
Me too!
