### ISSUE TITLE
No Firebase App '[DEFAULT]' has been created

### ISSUE THREAD

**Issue by snajperek130** [angular/angularfire2#550]
Hello, i have a weird problem. Yesterday everything was okay, today its not. I am using firebase with Angularfire2 and i do not know, what have happened. It is downloading data from firebase correctly(conosle.log is showing all objects) but when i i am trying to access to contact.name it is showing error: 

`error_handler.ts:62 Error: No Firebase App '[DEFAULT]' has been created - call Firebase App.initializeApp().
    at Error (native)
    at Z (http://localhost:3000/main.bundle.js:2036:331)
    at a (http://localhost:3000/main.bundle.js:2034:69)
    at Object.c [as storage] (http://localhost:3000/main.bundle.js:2035:447)
    at AvatarService.getAvatar (http://localhost:3000/main.bundle.js:16139:35)
    at AvatarComponent.set (http://localhost:3000/main.bundle.js:16087:32)
    at DebugAppView._View_ContactListComponent3.detectChangesInternal (ContactListComponent.ngfactory.js:510:35)
    at DebugAppView.AppView.detectChanges (http://localhost:3000/vendor.bundle.js:34155:14)
    at DebugAppView.detectChanges (http://localhost:3000/vendor.bundle.js:34260:44)
    at DebugAppView.AppView.detectContentChildrenChanges (http://localhost:3000/vendor.bundle.js:34173:19)
    at DebugAppView._View_ContactListComponent1.detectChangesInternal (ContactListComponent.ngfactory.js:313:8)
    at DebugAppView.AppView.detectChanges (http://localhost:3000/vendor.bundle.js:34155:14)
    at DebugAppView.detectChanges (http://localhost:3000/vendor.bundle.js:34260:44)
    at DebugAppView.AppView.detectContentChildrenChanges (http://localhost:3000/vendor.bundle.js:34173:19)
    at DebugAppView._View_ContactListComponent0.detectChangesInternal (ContactListComponent.ngfactory.js:111:8)
    at DebugAppView.AppView.detectChanges (http://localhost:3000/vendor.bundle.js:34155:14)
    at DebugAppView.detectChanges (http://localhost:3000/vendor.bundle.js:34260:44)
    at DebugAppView.AppView.detectViewChildrenChanges (http://localhost:3000/vendor.bundle.js:34181:19)
    at DebugAppView._View_ContactListComponent_Host0.detectChangesInternal (ContactListComponent_Host.ngfactory.js:31:8)
    at DebugAppView.AppView.detectChanges (http://localhost:3000/vendor.bundle.js:34155:14)
    at DebugAppView.detectChanges (http://localhost:3000/vendor.bundle.js:34260:44)
    at DebugAppView.AppView.detectContentChildrenChanges (http://localhost:3000/vendor.bundle.js:34173:19)
    at DebugAppView._View_App0.detectChangesInternal (App.ngfactory.js:240:8)
    at DebugAppView.AppView.detectChanges (http://localhost:3000/vendor.bundle.js:34155:14)
    at DebugAppView.detectChanges (http://localhost:3000/vendor.bundle.js:34260:44)
    at DebugAppView.AppView.detectViewChildrenChanges (http://localhost:3000/vendor.bundle.js:34181:19)
    at DebugAppView._View_App_Host0.detectChangesInternal (App_Host.ngfactory.js:31:8)
    at DebugAppView.AppView.detectChanges (http://localhost:3000/vendor.bundle.js:34155:14)
    at DebugAppView.detectChanges (http://localhost:3000/vendor.bundle.js:34260:44)
    at ViewRef_.detectChanges (http://localhost:3000/vendor.bundle.js:34643:65)
    at http://localhost:3000/vendor.bundle.js:26953:84
    at Array.forEach (native)
    at ApplicationRef_.tick (http://localhost:3000/vendor.bundle.js:26953:38)
    at http://localhost:3000/vendor.bundle.js:26894:105
    at ZoneDelegate.invoke (http://localhost:3000/polyfills.bundle.js:16126:28)
    at Object.onInvoke (http://localhost:3000/vendor.bundle.js:39601:41)
    at ZoneDelegate.invoke (http://localhost:3000/polyfills.bundle.js:16125:34)
    at Zone.run (http://localhost:3000/polyfills.bundle.js:16019:43)
    at NgZoneImpl.runInner (http://localhost:3000/vendor.bundle.js:39632:71)
    at NgZone.run (http://localhost:3000/vendor.bundle.js:39532:66)
    at Object.next (http://localhost:3000/vendor.bundle.js:26894:81)
    at SafeSubscriber.schedulerFn [as _next] (http://localhost:3000/vendor.bundle.js:31603:70)
    at SafeSubscriber.__tryOrUnsub (http://localhost:3000/vendor.bundle.js:112918:16)
    at SafeSubscriber.next (http://localhost:3000/vendor.bundle.js:112867:22)
    at Subscriber._next (http://localhost:3000/vendor.bundle.js:112820:26)
    at Subscriber.next (http://localhost:3000/vendor.bundle.js:112784:18)
    at EventEmitter.Subject.next (http://localhost:3000/vendor.bundle.js:112536:25)
    at EventEmitter.emit (http://localhost:3000/vendor.bundle.js:31595:76)
    at NgZone._checkStable (http://localhost:3000/vendor.bundle.js:39442:44)
    at NgZoneImpl.setMicrotask (http://localhost:3000/vendor.bundle.js:39418:23)
    at Object.onHasTask (http://localhost:3000/vendor.bundle.js:39613:35)
    at ZoneDelegate.hasTask (http://localhost:3000/polyfills.bundle.js:16185:55)
    at ZoneDelegate._updateTaskCount (http://localhost:3000/polyfills.bundle.js:16202:26)
    at ZoneDelegate.invokeTask (http://localhost:3000/polyfills.bundle.js:16163:26)
    at Zone.runTask (http://localhost:3000/polyfills.bundle.js:16059:47)
    at drainMicroTaskQueue (http://localhost:3000/polyfills.bundle.js:16291:35)`

It seems like i call .initializeApp() multiple times, but yesterday was everything okay.

app.module:
 ```
export const firebaseConfig = {
 // configurations
};
```
`imports: [AngularFireModule.initializeApp(firebaseConfig),...]`

contact.service:

```
public contacts: FirebaseListObservable<ContactWithKey[]>;
constructor(private af: AngularFire) {
  }
 getContacts() {
    this.contacts = this.af.database.list('data/contacts');
    this.af.database.list('data/contacts')
      .subscribe(data => console.log(data));
  }
```
ContactListComponent.html:
`<li *ngFor="let contact of contactService.contacts|async">
      {{contact.name}}`

**Comment by maxmumford** [comment]
I'm seeing this error too. Accessing data through the angularfire2 api works fine, but trying to access data off the firebase.auth() object like:

`firebase.auth().currentUser`

results in the following error:

```
Uncaught Error: No Firebase App '[DEFAULT]' has been created - call Firebase App.initializeApp()
```

**Comment by maxmumford** [comment]
I'm getting this issue as well, how did you solve it?
