### ISSUE TITLE
ZoneAwareError

### ISSUE THREAD

**Issue by Orkish** [angular/angularfire2#825]
Hey guys, i've been trying to just implement the simple tutorial app with Angular2 and firebase. 

Been following the guide to setting this up at https://github.com/angular/angularfire2/blob/master/docs/1-install-and-setup.md

No errors throw until I start my constructor in my ```app.component.ts: ``` :
```
import { Component } from '@angular/core';
import { AngularFire, FirebaseListObservable } from 'angularfire2';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.less']
})
export class AppComponent {
	title = 'app works!';
	artists: FirebaseListObservable<any[]>;

  constructor(private af: AngularFire) {
  
  }
}
```

Pretty sure everything in my ```app.module.ts``` is set up correctly:
```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';
import { firebaseConfig } from './../environments/firebase.config';
import { AngularFireModule } from 'angularfire2';

import { AppComponent } from './app.component';

@NgModule({
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule,
    AngularFireModule.initializeApp(firebaseConfig)
  ],
  declarations: [
    AppComponent
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

The error I am receiving is:
```
error_handler.js:54EXCEPTION: Cannot read property 'substring' of undefined
ErrorHandler.handleError @ error_handler.js:54
(anonymous) @ application_ref.js:261
ZoneDelegate.invoke @ zone.js:242
onInvoke @ ng_zone.js:273
ZoneDelegate.invoke @ zone.js:241
Zone.run @ zone.js:113
(anonymous) @ zone.js:535
ZoneDelegate.invokeTask @ zone.js:275
onInvokeTask @ ng_zone.js:264
ZoneDelegate.invokeTask @ zone.js:274
Zone.runTask @ zone.js:151
drainMicroTaskQueue @ zone.js:433
error_handler.js:59ORIGINAL STACKTRACE:
ErrorHandler.handleError @ error_handler.js:59
(anonymous) @ application_ref.js:261
ZoneDelegate.invoke @ zone.js:242
onInvoke @ ng_zone.js:273
ZoneDelegate.invoke @ zone.js:241
Zone.run @ zone.js:113
(anonymous) @ zone.js:535
ZoneDelegate.invokeTask @ zone.js:275
onInvokeTask @ ng_zone.js:264
ZoneDelegate.invokeTask @ zone.js:274
Zone.runTask @ zone.js:151
drainMicroTaskQueue @ zone.js:433
error_handler.js:60TypeError: Cannot read property 'substring' of undefined
    at Object.stripTrailingSlash [as a] (http://localhost:4200/vendor.bundle.js:81224:14)
    at _getDefaultFirebase (http://localhost:4200/vendor.bundle.js:82448:92)
    at AppModuleInjector.get (/AppModule/module.ngfactory.js:161:79)
    at AppModuleInjector.get (/AppModule/module.ngfactory.js:201:93)
    at AppModuleInjector.getInternal (/AppModule/module.ngfactory.js:272:51)
    at AppModuleInjector.NgModuleInjector.get (http://localhost:4200/vendor.bundle.js:53931:44)
    at CompiledTemplate.proxyViewClass.AppView.injectorGet (http://localhost:4200/vendor.bundle.js:72141:45)
    at CompiledTemplate.proxyViewClass.DebugAppView.injectorGet (http://localhost:4200/vendor.bundle.js:72569:49)
    at CompiledTemplate.proxyViewClass.View_AppComponent_Host0.createInternal (/AppModule/AppComponent/host.ngfactory.js:15:63)
    at CompiledTemplate.proxyViewClass.AppView.createHostView (http://localhost:4200/vendor.bundle.js:72097:21)
    at CompiledTemplate.proxyViewClass.DebugAppView.createHostView (http://localhost:4200/vendor.bundle.js:72553:52)
    at ComponentFactory.create (http://localhost:4200/vendor.bundle.js:38612:25)
    at ApplicationRef_.bootstrap (http://localhost:4200/vendor.bundle.js:36546:57)
    at http://localhost:4200/vendor.bundle.js:36365:89
    at Array.forEach (native)
ErrorHandler.handleError @ error_handler.js:60
(anonymous) @ application_ref.js:261
ZoneDelegate.invoke @ zone.js:242
onInvoke @ ng_zone.js:273
ZoneDelegate.invoke @ zone.js:241
Zone.run @ zone.js:113
(anonymous) @ zone.js:535
ZoneDelegate.invokeTask @ zone.js:275
onInvokeTask @ ng_zone.js:264
ZoneDelegate.invokeTask @ zone.js:274
Zone.runTask @ zone.js:151
drainMicroTaskQueue @ zone.js:433
zone.js:420 Unhandled Promise rejection: Cannot read property 'substring' of undefined ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read property 'substring' of undefined
    at Object.stripTrailingSlash [as a] (http://localhost:4200/vendor.bundle.js:81224:14)
    at _getDefaultFirebase (http://localhost:4200/vendor.bundle.js:82448:92)
    at AppModuleInjector.get (/AppModule/module.ngfactory.js:161:79)
    at AppModuleInjector.get (/AppModule/module.ngfactory.js:201:93)
    at AppModuleInjector.getInternal (/AppModule/module.ngfactory.js:272:51)
    at AppModuleInjector.NgModuleInjector.get (http://localhost:4200/vendor.bundle.js:53931:44)
    at CompiledTemplate.proxyViewClass.AppView.injectorGet (http://localhost:4200/vendor.bundle.js:72141:45)
    at CompiledTemplate.proxyViewClass.DebugAppView.injectorGet (http://localhost:4200/vendor.bundle.js:72569:49)
    at CompiledTemplate.proxyViewClass.View_AppComponent_Host0.createInternal (/AppModule/AppComponent/host.ngfactory.js:15:63)
    at CompiledTemplate.proxyViewClass.AppView.createHostView (http://localhost:4200/vendor.bundle.js:72097:21)
    at CompiledTemplate.proxyViewClass.DebugAppView.createHostView (http://localhost:4200/vendor.bundle.js:72553:52)
    at ComponentFactory.create (http://localhost:4200/vendor.bundle.js:38612:25)
    at ApplicationRef_.bootstrap (http://localhost:4200/vendor.bundle.js:36546:57)
    at http://localhost:4200/vendor.bundle.js:36365:89
    at Array.forEach (native) TypeError: Cannot read property 'substring' of undefined
    at Object.stripTrailingSlash [as a] (http://localhost:4200/vendor.bundle.js:81224:14)
    at _getDefaultFirebase (http://localhost:4200/vendor.bundle.js:82448:92)
    at AppModuleInjector.get (/AppModule/module.ngfactory.js:161:79)
    at AppModuleInjector.get (/AppModule/module.ngfactory.js:201:93)
    at AppModuleInjector.getInternal (/AppModule/module.ngfactory.js:272:51)
    at AppModuleInjector.NgModuleInjector.get (http://localhost:4200/vendor.bundle.js:53931:44)
    at CompiledTemplate.proxyViewClass.AppView.injectorGet (http://localhost:4200/vendor.bundle.js:72141:45)
    at CompiledTemplate.proxyViewClass.DebugAppView.injectorGet (http://localhost:4200/vendor.bundle.js:72569:49)
    at CompiledTemplate.proxyViewClass.View_AppComponent_Host0.createInternal (/AppModule/AppComponent/host.ngfactory.js:15:63)
    at CompiledTemplate.proxyViewClass.AppView.createHostView (http://localhost:4200/vendor.bundle.js:72097:21)
    at CompiledTemplate.proxyViewClass.DebugAppView.createHostView (http://localhost:4200/vendor.bundle.js:72553:52)
    at ComponentFactory.create (http://localhost:4200/vendor.bundle.js:38612:25)
    at ApplicationRef_.bootstrap (http://localhost:4200/vendor.bundle.js:36546:57)
    at http://localhost:4200/vendor.bundle.js:36365:89
    at Array.forEach (native)
consoleError @ zone.js:420
_loop_1 @ zone.js:449
drainMicroTaskQueue @ zone.js:453
zone.js:422 ZoneAwareError {__zone_symbol__error: Error: Uncaught (in promise): TypeError: Cannot read property 'substring' of undefined
TypeError: Ca…, rejection: TypeError: Cannot read property 'substring' of undefined
    at Object.stripTrailingSlash [as a] (ht…, promise: ZoneAwarePromise, zone: Zone, task: ZoneTask}
consoleError @ zone.js:422
_loop_1 @ zone.js:449
drainMicroTaskQueue @ zone.js:453
bridge.js:1 Connecting to PORT_NAME_SYMANTEC_PKI_CLIENT_CONTENT_TO_BACKGROUND...
bridge.js:1 Connected: Port {}
bridge.js:1 Done.
detection.js:1 +content/detection.js
detection.js:1 -content/detection.js
```

It only seems to break when I pass in af into the constructor argument. Any help would be greatly appreciated. Or if more details are needed please let me know.

Thanks!

**Comment by mukesh51** [comment]
@Orkish You're not following issue template, so it's difficult to analyse your problem. I just followed the tutorial and it works absolutely fine for me.

This is my configuration on windows 7 operating system

```
angular-cli: 1.0.0-beta.28.3
node: 6.9.1
os: win32 ia32

"angularfire2": "^2.0.0-beta.7",
"firebase": "^3.6.9"
```

What's your's ? It will be easy, if you can follow the issue template and provide all information.

**Comment by Orkish** [comment]
@mukesh51 Sorry about that:
```
angular-cli: 1.0.0-beta.28.3
node: 7.4.0
os: darwin x64

"angularfire2": "^2.0.0-beta.7",
"firebase": "^3.6.9"
```
So I think this may be an issue with how I initially installed it. Tried it on a different machine and it worked just fine. Just confused by the zone issue. Maybe I need to update my zone js?

Thanks!

**Comment by mukesh51** [comment]
@Orkish Great to hear, it's working. If everything is OK, I guess you can close this issue.

**Comment by Orkish** [comment]
@mukesh51 It's still not working on my local machine and I cannot figure out why. I've done same step on a different machine and it works. Let me try to figure this out then i'll create an in depth review of my issue/solution

**Comment by mukesh51** [comment]
Fair enough. This is how my package.json looks like and is working locally. let me know, how it works out for you.

```
"dependencies": {
    "@angular/common": "^2.3.1",
    "@angular/compiler": "^2.3.1",
    "@angular/core": "^2.3.1",
    "@angular/forms": "^2.3.1",
    "@angular/http": "^2.3.1",
    "@angular/platform-browser": "^2.3.1",
    "@angular/platform-browser-dynamic": "^2.3.1",
    "@angular/router": "^3.3.1",
    "angularfire2": "^2.0.0-beta.7",
    "core-js": "^2.4.1",
    "firebase": "^3.6.9",
    "rxjs": "^5.0.1",
    "ts-helpers": "^1.1.1",
    "zone.js": "^0.7.2"
  },
  "devDependencies": {
    "@angular/compiler-cli": "^2.3.1",
    "@types/jasmine": "2.5.38",
    "@types/node": "^6.0.42",
    "angular-cli": "1.0.0-beta.28.3",
    "codelyzer": "~2.0.0-beta.1",
    "jasmine-core": "2.5.2",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "1.2.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.2.1",
    "protractor": "~4.0.13",
    "ts-node": "1.2.1",
    "tslint": "^4.3.0",
    "typescript": "~2.0.3"
  }
```

**Comment by Orkish** [comment]
I dont think it's my package json, it might be something deeper. Am looking.

**Comment by Orkish** [comment]
Seems like my work computer is behind some sort of endpoint protection which prevents the completion of the handshake with firebase API. Even after shutting down my firewall and syematec protection, the connection was still refused.

This has nothing to do with the actual library or the tutorial.

Thanks for bearing with me.

Closing issue

**Comment by kleeb** [comment]
Having the same problem:

```
TypeError: Cannot read property 'substring' of null
    at stripTrailingSlash (main.js:4)
    at _getDefaultFirebase (main.js:5)
    at t.get [as _FirebaseConfig_56] (main.js:115)
    at t.get [as _AngularFire_64] (main.js:115)
    at t.get [as _FirebaseProvider_93] (main.js:115)
```

only when I am building Ionic2 bundle in the release/prod mode.

    "angularfire2": "2.0.0-beta.7",
    "firebase": "3.4.0"

**Comment by ravivit9** [comment]
Hi, I am also having similar zone aware error.
package.json
==========
"dependencies": {
    "@angular/common": "~2.4.0",
    "@angular/compiler": "~2.4.0",
    "@angular/core": "~2.4.0",
    "@angular/forms": "~2.4.0",
    "@angular/http": "~2.4.0",
    "@angular/material": "^2.0.0-beta.2",
    "@angular/platform-browser": "~2.4.0",
    "@angular/platform-browser-dynamic": "~2.4.0",
    "@angular/router": "~3.4.0",
    "angular-in-memory-web-api": "~0.3.1",
    "angularfire2": "^2.0.0-beta.8",
    "core-js": "^2.4.1",
    "firebase": "^3.7.2",
    "rxjs": "5.2.0",
    "systemjs": "0.20.10",
    "zone.js": "^0.7.8"
  },
  "devDependencies": {
    "concurrently": "^3.2.0",
    "lite-server": "^2.2.2",
    "typescript": "~2.2.1",
    "canonical-path": "0.0.2",
    "tslint": "^4.5.1",
    "lodash": "^4.16.4",
    "jasmine-core": "~2.5.2",
    "karma": "^1.3.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.1",
    "rimraf": "^2.5.4",
    "@types/node": "^7.0.8",
    "@types/jasmine": "2.5.46"
  },


![screen shot 2017-03-17 at 11 14 18](https://cloud.githubusercontent.com/assets/3435829/24040855/e78a0fb0-0b02-11e7-9d63-b72022bc673b.png)

**Comment by ravivit9** [comment]
Just started with Angular2, MD, Firebase.  Able to run the initial app running but without firebase.  The moment I import angularfire2 then the app fails with the above screenshot of 404 (not found).

Appreciate any help to resolve.  I am running in Mac.

**Comment by Orkish** [comment]
So if you made sure your packages all matched up with what I have and what the above commenter has first. If you're still getting the zone issue then I would recommend you nuke your node_modules directory and reinstall everything. 

My issue was a bit unique in that my work laptop prevents certain connections for happening. Even after I've disabled my firewall and symtec protection, the connection to the firebase api was still not connecting. If you read into the actual error, it should say which service is blocking it. 

I tried on a coworker's computer starting the same project from scratch and he ran into the issue as well with firebase. However, when I ran it on my personal machine, I was able to successfully retrieve data from firebase no problem. 

So, if all else fails, see if it's a security issue that's throwing the error.

Thanks, hope this helps.

**Comment by ravivit9** [comment]
Did the following:

rm -rf node_modules
npm clean cache
npm install
npm start

![screen shot 2017-03-17 at 11 14 18](https://cloud.githubusercontent.com/assets/3435829/24045276/66f13dec-0b16-11e7-859b-3ee5f2030814.png)

The web browser started but throws the above screenshot error again.   For some reason the app is not able to find angularfire2 to load.  Not sure where to specify to look for angularfire2.

In fact today morning only I created a new repository and installed one by one AJS2, MD2, FB2.  without FB2 the app works fine.

**Comment by ravivit9** [comment]
I did managed to run the app after a few try.  

I tried to follow the link https://medium.com/codingthesmartway-com-blog/angular-2-firebase-introduction-b4f32e844db2#.89d12414s which worked perfectly fine without any issue.

Thanks.

**Comment by Celleb** [comment]
I had an issue with loading angularfire2 with Ionic. I had my config messed up, instead of databaseURL I had databaseUrl. Only figured it out when I looked at the Javascript file that produced the error.

**Comment by evanplaice** [comment]
I experienced the same issue. Was using 0.7.6. Rolling back to "zone.js": "^0.7.2" fixed the issue. Eventually, rolled back to 0.6.8 to match the same version that Angular had listed in its dependencies.

I suspect that if you install a version that is different from the one that Angular depends on, it's going to cause issues.
