### ISSUE TITLE
sourcemap path error

### ISSUE THREAD

**Issue by GitHubish** [angular/angularfire2#94]
Hello,

I have an error when my app load angularfire2 with systemjs.

**error:** 

```
angular2-polyfills.js:322 Error: SyntaxError: Unexpected token <
	    at Object.eval (http://localhost:8000/node_modules/angularfire2/angularfire2.js:14:14)
	    at eval (http://localhost:8000/node_modules/angularfire2/angularfire2.js:62:4)
	Evaluating http://localhost:8000/node_modules/angularfire2/providers/auth
	Evaluating http://localhost:8000/node_modules/angularfire2/angularfire2.js
	Error loading http://localhost:8000/app/main.jsZoneDelegate.invoke @ angular2-polyfills.js:322Zone.run @ angular2-polyfills.js:218(anonymous function) @ angular2-polyfills.js:567ZoneDelegate.invokeTask @ angular2-polyfills.js:355Zone.runTask @ angular2-polyfills.js:254drainMicroTaskQueue @ angular2-polyfills.js:473ZoneTask.invoke @ angular2-polyfills.js:425
```

**config systemjs index.html:**

```html    
<script>
        System.config({
        packages: {        
          app: {
            format: 'register',
            defaultExtension: 'js'
          }
        },
        map: { 
            'd3' : '../node_modules/d3/d3.js',
            'angularfire2': '../node_modules/angularfire2/angularfire2.js'
        } 
      });
      System.import('app/main')
            .then(null, console.error.bind(console));
</script>
```

**main.ts**
```ts
import {Component} from 'angular2/core';
import {bootstrap}    from 'angular2/platform/browser'
import {AppComponent} from './app.component'
import {Observable} from 'rxjs/Observable';
import {FIREBASE_PROVIDERS, defaultFirebase} from 'angularfire2';

bootstrap(AppComponent, [
    // Common injectable providers from the AngularFire lib
    FIREBASE_PROVIDERS,
    // Tell AngularFire the base URL for the Firebase used throughout
    defaultFirebase('https://sweltering-inferno-45.firebaseio.com')
]);
```

when i run _npm install --save angularfire2_ i notice that angularfire2.js.map contains 
`... "sources":["../src/angularfire2.ts"]...`
src it's not good.

What I did not understand ?
thanks

**Comment by davideast** [comment]
I'm not sure what's going on, but can you try again with the latest version? We've made some updates and that may help the situation or at least get us on the same playing field.

**Comment by GitHubish** [comment]
it's good, I have all started with angular-cli from the beginning and I have no error. Thank you
