### ISSUE TITLE
AOT bug with Angular 4

### ISSUE THREAD

**Issue by evanjmg** [angular/angularfire2#957]
I was trying to run AOT with the latest angularfire2 and Angular 4 and I get this:
I get it in Heroku and locally 
``` > ngc -p ./tsconfig-aot.json && AOT=true npm run build:prod
       
       Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol Injectable in /tmp/build_440b726127025e250b151e94b9c01728/project-81455e54fdbbdb644b597c3f890b6cb584ab30ea/node_modules/angularfire2/node_modules/@angular/core/src/di/metadata.d.ts, resolving symbol Injectable in /tmp/build_440b726127025e250b151e94b9c01728/project-81455e54fdbbdb644b597c3f890b6cb584ab30ea/node_modules/angularfire2/node_modules/@angular/core/src/di.d.ts, resolving symbol Injectable in /tmp/build_440b726127025e250b151e94b9c01728/project-81455e54fdbbdb644b597c3f890b6cb584ab30ea/node_modules/angularfire2/node_modules/@angular/core/src/core.d.ts, resolving symbol Injectable in /tmp/build_440b726127025e250b151e94b9c01728/project-81455e54fdbbdb644b597c3f890b6cb584ab30ea/node_modules/angularfire2/node_modules/@angular/core/index.d.ts, resolving symbol AngularFireAuth in /tmp/build_440b726127025e250b151e94b9c01728/project-81455e54fdbbdb644b597c3f890b6cb584ab30ea/node_modules/angularfire2/auth/auth.d.ts, resolving symbol AngularFireAuth in /tmp/build_440b726127025e250b151e94b9c01728/VelocityMobile-WebERB-81455e54fdbbdb644b597c3f890b6cb584ab30ea/node_modules/angularfire2/auth/auth.d.ts
```
### Version info

**Angular: Angular 4.0.2 

**Firebase: 3.6.9

**AngularFire: latest - fixing it I downgraded to 2.0.0-beta.7

### Expected behavior
 It works.
### Actual behavior
It throws and error and can't compile

**Comment by davideast** [comment]
@evanjmg I'm going to need to see more. Can you show your `@NgModule` code?

**Comment by kabus202** [comment]
Same issue here, downgrading fixes the problem

**Comment by ravivit9** [comment]
I followed instructions up to Bookmarks as per the link https://angular.io/docs/ts/latest/cookbook/aot-compiler.html#!#bootstrap

The following error occurred while doing ng serve.  Please note that ngc compile left with 1 compilation error as .../src/app/app.component.ts:15:22: Cannot find name 'System'.

 
Error: Tried to find bootstrap code, but could not. Specify either statically analyzable bootstrap code or pass in an entryModule to the plugins options
    at Object.resolveEntryModuleFromMain (/Users/ravindra/work/ajs/node_modules/@ngtools/webpack/src/entry_resolver.js:128:11)
    at AotPlugin._setupOptions (/Users/ravindra/work/ajs/node_modules/@ngtools/webpack/src/plugin.js:143:50)
    at new AotPlugin (/Users/ravindra/work/ajs/node_modules/@ngtools/webpack/src/plugin.js:26:14)
    at _createAotPlugin (/Users/ravindra/work/ajs/node_modules/@angular/cli/models/webpack-configs/typescript.js:55:12)
    at Object.exports.getNonAotConfig (/Users/ravindra/work/ajs/node_modules/@angular/cli/models/webpack-configs/typescript.js:70:19)
    at NgCliWebpackConfig.buildConfig (/Users/ravindra/work/ajs/node_modules/@angular/cli/models/webpack-config.js:27:37)
    at Class.run (/Users/ravindra/work/ajs/node_modules/@angular/cli/tasks/serve.js:37:98)
    at check_port_1.checkPort.then.port (/Users/ravindra/work/ajs/node_modules/@angular/cli/commands/serve.js:103:26)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by jamesdaniels** [comment]
Having no trouble with --aot and the version of latest everything. Going to close. If you find it's still a problem a repro / PR would be super helpful.

**Comment by gusdevops** [comment]
@kabus202  How can I do that?
